[package]
name = "simple_worker"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fang = { path = "../../" }
serde = { version = "1.0", features = ["derive"] }
dotenv = "0.15.0"
