name: Rust Code Formatting

on:
  push:
  pull_request:
    types: [opened, reopened]

jobs:
  rustfmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    strategy:
      matrix:
        toolchain:
          - stable
    steps:
      - uses: actions/checkout@v3

      - name: Setup Rust
        run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}

      - name: Check format
        run: cargo fmt -- --check --verbose
